// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amkfdpyuaurfarxcrodx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFta2ZkcHl1YXVyZmFyeGNyb2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDUxNzUsImV4cCI6MjA2NjYyMTE3NX0.z-NzXBcb93C9uM42eoNyugLh2iKnt2Kd6gVQ-O6LGMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});